{
  "controlTypeValues": {},
  "controlClassValues": {
    "myVerticalTab": {
      "attributes": {},
      "themedResources": {}
    },
    "myTabHeight1": {
      "attributes": {},
      "themedResources": {}
    },
    "myTabHeight2": {
      "attributes": {},
      "themedResources": {}
    }
  },
  "$schema": "./../../../Packages/Beckhoff.TwinCAT.HMI.Framework.12.760.48/runtimes/native1.12-tchmi/Schema/ThemeDescription.Schema.json"
}